[build]
builder = "NIXPACKS"

[deploy]
startCommand = "java -jar build/libs/jhlee-vive-coding-be-0.0.1-SNAPSHOT.jar"
healthcheckPath = "/api/auth/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
